### ISSUE TITLE
imgboxのキャプションをfigcaptionにしたい

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-markdown#14]
noteやcolumnと違い、figure要素になるimgboxにはfigcaptionという要素があるのでそれ使いたいなと。

**Comment by nakajmg** [comment]
https://github.com/pxgrid/codegrid-markdown/blob/06fbf59203cb8e51848df70762eaf4b54ae41d08/lib/renderer/cgmd/imgbox.js#L4-L7
ここの変更でいけそう

**Comment by leader22** [comment]
`codegrid-components`で実現済

![image](https://user-images.githubusercontent.com/6259812/104695356-fcc90f00-574f-11eb-8993-b34576e86529.png)
