### ISSUE TITLE
コードブロックのタイトルの前にスペースを入れたい

### ISSUE THREAD

**Issue by myakura** [pxgrid/codegrid-markdown#16]
![スクリーンショット：タイトル付きコードブロックをエディタで見たところ](https://user-images.githubusercontent.com/413984/54157790-5beed600-448c-11e9-8e99-8d750d88e1be.png)

シンタックスハイライトが効かなくなってあまりこの機能を使いたくない。スペースを入れると回避できるので、このライブラリ側でもスペース使えるようにしたい。

**Comment by leader22** [comment]
これはたぶんできるので、やるます

**Comment by leader22** [comment]
````md

これと

```js #title
const a = 1;
```

これの

```js#title
const a = 1;
```

出力は等価になる
````
